/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetIpPortRouteImport } from './routes/asset.$ip.$port'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIpPortRoute = AssetIpPortRouteImport.update({
  id: '/asset/$ip/$port',
  path: '/asset/$ip/$port',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asset/$ip/$port': typeof AssetIpPortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asset/$ip/$port': typeof AssetIpPortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asset/$ip/$port': typeof AssetIpPortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asset/$ip/$port'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asset/$ip/$port'
  id: '__root__' | '/' | '/asset/$ip/$port'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetIpPortRoute: typeof AssetIpPortRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$ip/$port': {
      id: '/asset/$ip/$port'
      path: '/asset/$ip/$port'
      fullPath: '/asset/$ip/$port'
      preLoaderRoute: typeof AssetIpPortRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetIpPortRoute: AssetIpPortRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
